apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
type: Opaque
data:
  # echo -n 'postgresql://user:pass@db:5432/app' | base64
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0BkYjo1NDMyL2FwcA==
